apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xrc11hqzj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xrc11hqzj-nodejs 
  name: xrc11hqzj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xrc11hqzj-nodejs 
